/*MONCLOVA SUANO RAFAEL*/
DROP DATABASE IF EXISTS fotografia;
CREATE DATABASE fotografia;
use fotografia;

DROP TABLE IF EXISTS fotografia.CAMARA;
DROP TABLE IF EXISTS fotografia.ACCESORIO;
DROP TABLE IF EXISTS fotografia.CLIENTE;


CREATE TABLE CLIENTE (

	DNI					CHAR(9) NOT NULL PRIMARY KEY ,
	NOMBRE				CHAR(20) NOT NULL ,
	APELLIDOS			VARCHAR(30) NOT NULL ,
	DIRECCION			VARCHAR(50) NOT NULL ,
	TELEFONO			INT UNSIGNED NOT NULL ,
	HABITUAL			BOOLEAN NOT NULL,
	IMAGEN				LONGBLOB

) engine = innoDB;

CREATE TABLE ACCESORIO (

	ID					SMALLINT UNSIGNED NOT NULL PRIMARY KEY ,
	MARCA				VARCHAR(20) NULL ,	
	MODELO				VARCHAR(50) NOT NULL UNIQUE,
	PRECIO				DECIMAL(6,2) NOT NULL,
	TIPO				VARCHAR(20) NOT NULL ,
	IMAGEN				LONGBLOB	


) engine = innoDB;

CREATE TABLE CAMARA (

	ID					SMALLINT UNSIGNED NOT NULL PRIMARY KEY ,
	MARCA				VARCHAR(20) NULL ,	
	MODELO				VARCHAR(50) NOT NULL UNIQUE,
	PRECIO				DECIMAL(8,2) NOT NULL,
	IMAGEN				LONGBLOB 


) engine = innoDB;

CREATE TABLE COMPRA (

	CODIGO				SMALLINT UNSIGNED NOT NULL PRIMARY KEY ,
	MODELO				VARCHAR(50) NOT NULL UNIQUE,	
	CANTIDAD			INT NOT NULL ,
	PRECIO				DECIMAL(8,2) NOT NULL,

	CONSTRAINT FK_COMPRA_CAMARA
	FOREIGN KEY (MODELO)
	REFERENCES fotografia.CAMARA (MODELO)
	ON DELETE NO ACTION ON UPDATE NO ACTION ,

	CONSTRAINT FK_COMPRA_ACCESORIO
	FOREIGN KEY (MODELO)
	REFERENCES fotografia.ACCESORIO (MODELO)
	ON DELETE NO ACTION  ON UPDATE NO ACTION  


) engine = innoDB;

CREATE TABLE FACTURA (

	CODIGO				SMALLINT UNSIGNED NOT NULL PRIMARY KEY ,
	DNI					CHAR(9) NOT NULL ,
	COMPRAS				VARCHAR(1000) NOT NULL,	
	PRECIO_TOTAL		DECIMAL(8,2) NOT NULL

	 

) engine = innoDB;

SET GLOBAL FOREIGN_KEY_CHECKS=0;
